package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalTime;

public class GUIPanelMensaje extends javax.swing.JPanel {

    String contenido=null;
    LocalTime hora=null;
    Boolean propio=null;
    
    /**
     * Creates new form GUIPanelMensaje
     */
    public GUIPanelMensaje(String contenido, LocalTime hora, Boolean propio) {
        initComponents();
        
        this.contenido=contenido;
        this.propio=propio;
        jTextArea1.setText(contenido);
        jTextField1.setText(String.format("%d:%02d", hora.getHour(), hora.getMinute()));
        jTextField1.setVisible(true);
        this.setPropio(propio);
    }
    
    public void setPropio(Boolean propio){
    
        if(propio){
            this.remove(jPanel1);
            this.add(jPanel1, BorderLayout.EAST);
            jTextArea1.setBackground(Color.CYAN);
        }else{
            this.remove(jPanel1);
            this.add(jPanel1, BorderLayout.WEST);
            jTextArea1.setBackground(Color.WHITE);
        }
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(500, 100));
        setMinimumSize(new java.awt.Dimension(500, 100));
        setPreferredSize(new java.awt.Dimension(500, 100));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(261, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(261, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(261, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextField1.setMaximumSize(new java.awt.Dimension(90, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(90, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(90, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(261, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(261, 20));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(261, 20));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 204, 255));
        jTextArea1.setColumns(1);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(1);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(6, 2, 6, 2));
        jTextArea1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jTextArea1.setMinimumSize(new java.awt.Dimension(261, 20));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
